DROP TABLE IF EXISTS javascript_groups;
DROP TABLE IF EXISTS javascript_users;

DROP TABLE IF EXISTS NODE_CONNECTION;
DROP TABLE IF EXISTS NETWORK_NODE;
DROP TABLE IF EXISTS NETWORK;
DROP TABLE IF EXISTS SOLUTION_VARIABLE;
DROP TABLE IF EXISTS SOLUTION;
DROP TABLE IF EXISTS SIMULATION_ITERATION;
DROP TABLE IF EXISTS SIMULATION;
DROP TABLE IF EXISTS EXPERIMENT_PARAMETERS;
DROP TABLE IF EXISTS PARAMETER;
DROP TABLE IF EXISTS EXPERIMENT;



